<a href="https://colab.research.google.com/github/lakesidetech/machine_learning/blob/main/Weights_KNN_alogirthm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
#sklearn library metrics class
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandas import read_csv
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, f1_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import preprocessing



In [3]:
#read dataset
weights = pd.read_csv("/content/weight_info.csv")
weights

Weight(x2)  Height(y2)        Class
0          52         167  Underweight
1          62         186       Normal
2          69         176       Normal
3          64         173       Normal
4          65         172       Normal
5          56         174  Underweight
6          58         169       Normal
7          57         173       Normal
8          55         170       Normal

# **Data Visualization and Analysis**

In [4]:
#data shape - number of rows and columns example 9 roes and 3 cloumns
weights.shape

(9, 3)

In [5]:
#how many values belongs to each class
weights['Class'].value_counts()

Normal         7
Underweight    2
Name: Class, dtype: int64

In [6]:
#gives the names of all the columns
weights.columns

Index(['Weight(x2)', 'Height(y2)', 'Class'], dtype='object')

In [7]:
#givesall the values in the dataset weights
weights.values

array([[52, 167, 'Underweight'],
       [62, 186, 'Normal'],
       [69, 176, 'Normal'],
       [64, 173, 'Normal'],
       [65, 172, 'Normal'],
       [56, 174, 'Underweight'],
       [58, 169, 'Normal'],
       [57, 173, 'Normal'],
       [55, 170, 'Normal']], dtype=object)

In [8]:
#information about the dataset including memory usage, number of columns, null or non-null values, datatype
weights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Weight(x2)  9 non-null      int64 
 1   Height(y2)  9 non-null      int64 
 2   Class       9 non-null      object
dtypes: int64(2), object(1)
memory usage: 344.0+ bytes


In [10]:
#displays the X values
X=weights.iloc[:,:2]
X

Weight(x2)  Height(y2)
0          52         167
1          62         186
2          69         176
3          64         173
4          65         172
5          56         174
6          58         169
7          57         173
8          55         170

In [12]:
#y values ommit the collon
y=weights.iloc[:,-1]
y

0    Underweight
1         Normal
2         Normal
3         Normal
4         Normal
5    Underweight
6         Normal
7         Normal
8         Normal
Name: Class, dtype: object

# **DATA NORMALIZATION**

In [18]:
X=preprocessing.StandardScaler().fit_transform(X)
X[0:2]


array([[-1.4951259 , -1.22644473],
       [ 0.42717883,  2.45288945]])

**TRAIN TEST SPLIT**

In [19]:
#in classification you take 70% for training and 30% for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)
y_test.shape #number of rows in the test-size

(3,)

**Training and Predicting**

In [21]:
knn_model=KNeighborsClassifier(n_neighbors=3) 
knn_model.fit(X_train,y_train)
y_prediction=knn_model.predict(X_test)

# **Accuracy**

In [24]:
#find accuracy of the model
accuracy1=accuracy_score(y_test,y_prediction)
accuracy1

1.0

In [26]:
#confusion matrix
cm=confusion_matrix(y_test.values,y_prediction)
cm

array([[3]])